iris.features.optional = ENTITY_TRANSLUCENT

clouds = fancy
oldLighting = false
vignette = false

screen = SHADOWS SKY_CLOUDS [LIGHTING] [ATMOSPHERE] [CLOUDS]
screen.LIGHTING = LIGHTING_STRENGTH SPECULAR_STRENGTH RIM_LIGHT_STRENGTH BLOOM_STRENGTH STYLE_STRENGTH
screen.ATMOSPHERE = FOG_DENSITY ATMOSPHERE_STRENGTH
screen.CLOUDS = SKY_CLOUD_AMOUNT CUSTOM_CLOUDS CLOUD_OPACITY CLOUD_DETAIL

sliders = LIGHTING_STRENGTH SPECULAR_STRENGTH RIM_LIGHT_STRENGTH BLOOM_STRENGTH STYLE_STRENGTH FOG_DENSITY ATMOSPHERE_STRENGTH SKY_CLOUD_AMOUNT CLOUD_OPACITY CLOUD_DETAIL
